# This is a basic workflow that is manually triggered

name: Build the repository for certain commit

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
      VV8: "$(pwd)/visiblev8"
      WD: "$(pwd)/chrome"
    steps:
    - run: echo $VV8 \
          echo $WD
    # Runs a single command using the runners shell
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: mkdir $WD
    - name: Build the chrome
      run: $VV/builder/tool.py -d $WD checkout 5afa96dadfe803e8a058d6ede0c9c3987405b8d8
      
