# This is a basic workflow that is manually triggered

name: Build the repository for certain commit

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      commit:
        required: false
        default: 5afa96dadfe803e8a058d6ede0c9c3987405b8d8
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: vv8build
    env: 
      VV8: ${{github.workspace}}/visiblev8
      WD: ${{github.workspace}}/chrome
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: visiblev8
    - run: mkdir ${{env.WD}}
    - name: Build the chrome
      run: python3 ${{env.VV8}}/builder/tool.py -d ${{env.WD}} checkout ${{inputs.commit}}
    - name: Patch the Chromium
      run: patch -p1 <${{env.VV8}}/patches/5afa96dadfe803e8a058/trace-apis.diff
      working-directory: ${{env.WD}}/src/v8
    - name: Build the chromium
      run: ${{env.VV8}}/builder/tool.py -d ${{env.WD}} build @std
      shell: python
      
