# This is a basic workflow that is manually triggered

name: Build the repository for certain commit

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      commit:
        required: false
        default: 5afa96dadfe803e8a058d6ede0c9c3987405b8d8
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     env: 
#       VV8: "$GITHUB_WORKSPACE/visiblev8"
#       WD: "$GITHUB_WORKSPACE/chrome"
    steps:
    - run: echo $VV8
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: mkdir $GITHUB_WORKSPACE/chrome
    - name: Build the chrome
      run: python3 $GITHUB_WORKSPACE/builder/tool.py -d $GITHUB_WORKSPACE/chrome checkout ${inputs.commit}
      
