# This is a basic workflow that is manually triggered

name: Simple tests workflows

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: vv8build
    env:
      WD: ${{github.workspace}}/chrome
      VV8: ${{github.workspace}}/visiblev8
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Worksppace ${{ github.workspace }}"
    - run: echo $WD $VV8
